// MTR Light Rail Stations Data
const STATIONS = [
    { id: "1", nameEn: "Tuen Mun Ferry Pier", nameCh: "屯門碼頭" },
    { id: "10", nameEn: "Melody Garden", nameCh: "美樂" },
    { id: "15", nameEn: "Butterfly", nameCh: "蝴蝶" },
    { id: "20", nameEn: "Light Rail Depot", nameCh: "輕鐵車廠" },
    { id: "30", nameEn: "Lung Mun", nameCh: "龍門" },
    { id: "40", nameEn: "Tsing Shan Tsuen", nameCh: "青山村" },
    { id: "50", nameEn: "Tsing Wun", nameCh: "青雲" },
    { id: "60", nameEn: "Kin On", nameCh: "建安" },
    { id: "70", nameEn: "Ho Tin", nameCh: "河田" },
    { id: "75", nameEn: "Choy Yee Bridge", nameCh: "蔡意橋" },
    { id: "80", nameEn: "Affluence", nameCh: "澤豐" },
    { id: "90", nameEn: "Tuen Mun Hospital", nameCh: "屯門醫院" },
    { id: "100", nameEn: "Siu Hong", nameCh: "兆康" },
    { id: "110", nameEn: "Kei Lun", nameCh: "麒麟" },
    { id: "120", nameEn: "Ching Chung", nameCh: "青松" },
    { id: "130", nameEn: "Kin Sang", nameCh: "建生" },
    { id: "140", nameEn: "Tin King", nameCh: "田景" },
    { id: "150", nameEn: "Leung King", nameCh: "良景" },
    { id: "160", nameEn: "San Wai", nameCh: "新圍" },
    { id: "170", nameEn: "Shek Pai", nameCh: "石排" },
    { id: "180", nameEn: "Shan King(North)", nameCh: "山景(北)" },
    { id: "190", nameEn: "Shan King(South)", nameCh: "山景(南)" },
    { id: "200", nameEn: "Ming Kum", nameCh: "鳴琴" },
    { id: "212", nameEn: "Tai Hing(North)", nameCh: "大興(北)" },
    { id: "220", nameEn: "Tai Hing(South)", nameCh: "大興(南)" },
    { id: "230", nameEn: "Ngan Wai", nameCh: "銀圍" },
    { id: "240", nameEn: "Siu Hei", nameCh: "兆禧" },
    { id: "250", nameEn: "Tuen Mun Swimming Pool", nameCh: "屯門泳池" },
    { id: "260", nameEn: "Goodview Garden", nameCh: "豐景園" },
    { id: "265", nameEn: "Siu Lun", nameCh: "兆麟" },
    { id: "270", nameEn: "On Ting", nameCh: "安定" },
    { id: "275", nameEn: "Yau Oi", nameCh: "友愛" },
    { id: "280", nameEn: "Town Centre", nameCh: "市中心" },
    { id: "295", nameEn: "Tuen Mun", nameCh: "屯門" },
    { id: "300", nameEn: "Pui To", nameCh: "杯渡" },
    { id: "310", nameEn: "Hoh Fuk Tong", nameCh: "何福堂" },
    { id: "320", nameEn: "San Hui", nameCh: "新墟" },
    { id: "330", nameEn: "Prime View", nameCh: "景峰" },
    { id: "340", nameEn: "Fung Tei", nameCh: "鳳地" },
    { id: "350", nameEn: "Lam Tei", nameCh: "藍地" },
    { id: "360", nameEn: "Nai Wai", nameCh: "泥圍" },
    { id: "370", nameEn: "Chung Uk Tsuen", nameCh: "鍾屋村" },
    { id: "380", nameEn: "Hung Shui Kiu", nameCh: "洪水橋" },
    { id: "390", nameEn: "Tong Fong Tsuen", nameCh: "塘坊村" },
    { id: "400", nameEn: "Ping Shan", nameCh: "屏山" },
    { id: "425", nameEn: "Hang Mei Tsuen", nameCh: "坑尾村" },
    { id: "430", nameEn: "Tin Shui Wai", nameCh: "天水圍" },
    { id: "435", nameEn: "Tin Tsz", nameCh: "天慈" },
    { id: "445", nameEn: "Tin Yiu", nameCh: "天耀" },
    { id: "448", nameEn: "Locwood", nameCh: "樂湖" },
    { id: "450", nameEn: "Tin Wu", nameCh: "天湖" },
    { id: "455", nameEn: "Ginza", nameCh: "銀座" },
    { id: "460", nameEn: "Tin Shui", nameCh: "天瑞" },
    { id: "468", nameEn: "Chung Fu", nameCh: "頌富" },
    { id: "480", nameEn: "Tin Fu", nameCh: "天富" },
    { id: "490", nameEn: "Chestwood", nameCh: "翠湖" },
    { id: "500", nameEn: "Tin Wing", nameCh: "天榮" },
    { id: "510", nameEn: "Tin Yuet", nameCh: "天悅" },
    { id: "520", nameEn: "Tin Sau", nameCh: "天秀" },
    { id: "530", nameEn: "Wetland Park", nameCh: "濕地公園" },
    { id: "540", nameEn: "Tin Heng", nameCh: "天恒" },
    { id: "550", nameEn: "Tin Yat", nameCh: "天逸" },
    { id: "560", nameEn: "Shui Pin Wai", nameCh: "水邊圍" },
    { id: "570", nameEn: "Fung Nin Road", nameCh: "豐年路" },
    { id: "580", nameEn: "Hong Lok Road", nameCh: "康樂路" },
    { id: "590", nameEn: "Tai Tong Road", nameCh: "大棠路" },
    { id: "600", nameEn: "Yuen Long", nameCh: "元朗" },
    { id: "920", nameEn: "Sam Shing", nameCh: "三聖" }
];
